# Databricks notebook source
# MAGIC %md # CCU053-D03a-cohort
# MAGIC
# MAGIC **Project** CCU053
# MAGIC
# MAGIC **Description** This notebook loads the cohort - people diagnosed with diabetes type 1 and 2 - from the diabetes phenotype algorithm
# MAGIC
# MAGIC **Authors** Candidate 491922
# MAGIC
# MAGIC **Acknowledgements** Using dataset genereated by diabetes phenotype algorithm, developed by Fiona Chalmers as part of Diabetes Catalyst of the BHF Data Science Centre
# MAGIC https://github.com/BHFDSC/hds_phenotypes_diabetes 
# MAGIC
# MAGIC **Notes**
# MAGIC
# MAGIC **Data Output**
# MAGIC - **`ccu053_out_cohort`** : project cohort

# COMMAND ----------

# MAGIC %md # 0. Setup

# COMMAND ----------

spark.sql('CLEAR CACHE')
spark.conf.set('spark.sql.legacy.allowCreatingManagedTableUsingNonemptyLocation', 'true')

# COMMAND ----------

import pyspark.sql.functions as f
import pyspark.sql.types as t
from pyspark.sql import Window

from functools import reduce

import databricks.koalas as ks
import pandas as pd
import numpy as np

import re
import io
import datetime

import matplotlib
import matplotlib.pyplot as plt
from matplotlib import dates as mdates
import seaborn as sns

print("Matplotlib version: ", matplotlib.__version__)
print("Seaborn version: ", sns.__version__)
_datetimenow = datetime.datetime.now() # .strftime("%Y%m%d")
print(f"_datetimenow:  {_datetimenow}")

# COMMAND ----------

# MAGIC %run "../SHDS/common/functions"

# COMMAND ----------

# MAGIC %md #1. Parameters
# MAGIC

# COMMAND ----------

# MAGIC %run "./CCU053-D01-parameters"

# COMMAND ----------

# MAGIC %md # 2. Data
# MAGIC

# COMMAND ----------

# load cohort table generated by diabetes phenotype algorithm 
cohort_prev = spark.table(f'{dsa}.ddsc_cohort_out_2024_07')
cohort = spark.table(f'{dsa}.hds_ddsc_cohort_out_2024_12_02')

# COMMAND ----------

display(cohort)

# COMMAND ----------

count_var(cohort_prev, 'PERSON_ID'); print()

# COMMAND ----------

count_var(cohort, 'PERSON_ID'); print()

# COMMAND ----------

tab(cohort_prev,'out_diabetes');print();

# COMMAND ----------

tab(cohort,'out_diabetes');print();

# COMMAND ----------

# MAGIC %md # 3. Save
# MAGIC

# COMMAND ----------

save_table(cohort, out_name=f'{proj}_out_cohort')
